sys-kernel/bootengine: prevent boot loop on ignition failure
kinvolk/coreos-overlay pull request #1262
Opened 2021-09-07 08:38 UTC by jepio

# sys-kernel/bootengine: prevent boot loop on ignition failure

This fixes boot loops in initramfs we have been seeing when ignition fails. The emergency.target needs to be isolated to ensure other initramfs units don't continue booting. This is equivalent to this fix in CoreOS https://github.com/coreos/ignition-dracut/pull/188.

This pulls in https://github.com/kinvolk/bootengine/pull/28.
Fixes https://github.com/kinvolk/Flatcar/issues/434
Fixes https://github.com/kinvolk/Flatcar/issues/454

## How to use

Follow instructions in https://github.com/kinvolk/bootengine/pull/28.

## Testing done

CI pending.

2021-09-09 17:55 UTC, krnowak requested changes

2021-09-09 17:55 UTC, krnowak commented on sys-kernel/bootengine/bootengine-9999.ebuild
> +	CROS_WORKON_COMMIT="588d30a8ecefa804b75c92d43360ea9b7b6842d9" # TODO
```suggestion
	CROS_WORKON_COMMIT="589e6bec78718a25eaccc46f25d2c59763b91327" # flatcar-master
```

2021-09-10 08:22 UTC, jepio commented on sys-kernel/bootengine/bootengine-9999.ebuild
> +	CROS_WORKON_COMMIT="588d30a8ecefa804b75c92d43360ea9b7b6842d9" # TODO
Done

2021-09-10 08:23 UTC, sayanchowdhury approved these changes

2021-09-10 08:25 UTC, merged